# Generated by Django 6.0.2 on 2026-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
