# Generated by Django 4.2.11 on 2026-02-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('car_make_model', models.CharField(default='', max_length=150)),
                ('vin_chassis_number', models.CharField(default='', max_length=50)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('ppf_category', models.CharField(choices=[('GLOSS_6', 'Gloss PPF – 6 Years'), ('GLOSS_10', 'Gloss PPF – 10 Years'), ('MATTE_6', 'Matte PPF – 6 Years'), ('BLACK_6', 'Black PPF – 6 Years')], default='', max_length=20)),
                ('installer_studio_name', models.CharField(default='', max_length=150)),
                ('installation_proof', models.FileField(default='', upload_to='warranty/proof/')),
                ('car_front_view', models.ImageField(default='', upload_to='warranty/car_views/')),
                ('car_back_view', models.ImageField(default='', upload_to='warranty/car_views/')),
                ('car_left_view', models.ImageField(default='', upload_to='warranty/car_views/')),
                ('car_right_view', models.ImageField(default='', upload_to='warranty/car_views/')),
                ('car_roof_view', models.ImageField(default='', upload_to='warranty/car_views/')),
                ('approval_status', models.CharField(choices=[('NOT_APPROVED', 'Not Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_APPROVED', max_length=20)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('warranty_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
