# Generated by Django 6.0.2 on 2026-02-05 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('car_number', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(max_length=50)),
                ('camio_roll_unique_code', models.CharField(max_length=100, unique=True)),
                ('ppf_category', models.CharField(choices=[('GLOSS_6', 'Gloss PPF – 6 Years'), ('GLOSS_10', 'Gloss PPF – 10 Years'), ('MATTE_6', 'Matte PPF – 6 Years'), ('BLACK_6', 'Black PPF – 6 Years')], max_length=20)),
                ('approval_status', models.CharField(choices=[('NOT_APPROVED', 'Not Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_APPROVED', max_length=20)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('warranty_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('car_image_with_ppf', models.ImageField(upload_to='warranty/car_images/')),
                ('rc_photo', models.ImageField(upload_to='warranty/rc_photos/')),
                ('detailer_studio_name', models.CharField(max_length=150)),
                ('detailer_mobile_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
