# Generated by Django 4.2.11 on 2026-02-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warranty',
            old_name='camio_roll_unique_code',
            new_name='roliin_roll_unique_code',
        ),
    ]
