# Generated by Django 4.2.11 on 2026-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='ppf_variant',
            field=models.CharField(choices=[('PREMIUM_MATTE_SERIES', 'Premium Matte Series'), ('PREMIUM_GLOSS_SERIES', 'Premium Gloss Series'), ('TITANIUM_GLOSS_SERIES', 'Titanium Gloss Series'), ('PIANO_BLACK_COLOR_PPF_SERIES', 'Piano Black Color PPF Series'), ('CHARCOAL_BLACK_COLOR_PPF_SERIES', 'Charcoal Black Color PPF Series')], default='', max_length=100),
        ),
    ]
