# Generated by Django 4.2.11 on 2026-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='ppf_roll_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
